### ISSUE TITLE
Command.StandardOutput.ReadToEnd() hangs every time

### ISSUE THREAD

**Issue by xjfnet** [madelson/MedallionShell#12] opened 2017-06-03 15:38 UTC
```cs
    Process.GetProcessesByName("adb").ToList().ForEach(x => x.Kill());
    var arguments = new List<string> { "connect", "127.0.0.1:21503" };
    var command = Command.Run("adb.exe", arguments,
        options => options.Timeout(TimeSpan.FromMinitues(1)));
    var output = command.StandardOutput.ReadToEnd();
    var error = command.StandardError.ReadToEnd();
```

adb.exe is is Android Debug Bridge
1. the code snippet hangs every time with adb.exe version 1.0.31
2. options.Timeout does not work, the underline process still running after 1 minute
3. the code snippet works well with adb.exe version 1.0.39

**Comment by madelson** [comment] 2017-06-03 18:36
Hi @xjfnet. I have a few questions:

1. What version of MedallionShell are you running?
2. What OS and platform (e. g. .NET Framework 4.5, .NET Core 1.0, Mono, etc) are you using ?
3. When you say that it hangs every time, what line is it hanging on?
4. What happens when you do:
```
var command = Command.Run("adb.exe", arguments,
        options => options.Timeout(TimeSpan.FromMinutes(1)));
var result = command.Result;
var output = result.StandardOutput;
var error = result.StandardError;
```
?

**Comment by xjfnet** [comment] 2017-06-04 00:36
1. MedallionShell 1.3.0
2. Win10, NET Framework 4.5.2
3. command.StandardOutput.ReadToEnd()
4. command.Result.StandardOutput hangs

**Comment by madelson** [comment] 2017-06-04 12:03
@xjfnet interesting and thanks for the additional detail. Based on what you wrote, it sounds like `adb` is exiting normally; command.Result won't return until the process has exited.

That suggests to me that output is being stuck in the pipe somehow such that the output stream is not closing properly.

As I don't have that particular exe running on my machine, debugging this will be tricky. A few more things that would help:
1. What is the exit code you get `result.ExitCode`?
2. What is the output you expect from `adb.exe`?
3. If you first read from standard error, do you see anything there?
4. Instead of calling `ReadToEnd()`, what do you see if you read one character at a time:
```
int ch;
while ((ch = command.StandardOutput.Read()) != -1)
{
    // or some other way that you can see any output before the final call to Read() hangs
    Console.Write((char)ch);
    Console.Out.Flush();
}
```
5. One more thing to try would be to just kick off the process directly with the underlying API:
```
var process = new Process
    {
        StartInfo = 
        {
            FileName = "adb.exe",
            // in my case, these were some file paths and options
            Arguments = string.Join(" ", new[] { "connect", "127.0.0.1:21503" }),
            CreateNoWindow = true,
            RedirectStandardError = true,
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
        }
};
process.Start();
var outTask = Task.Run(() => process.StandardOutput.ReadToEndAsync());
var errTask = Task.Run(() => process.StandardError.ReadToEndAsync());
process.WaitForExit();
var outText = outTask.Result;
var errText = errTask.Result;
```

**Comment by xjfnet** [comment] 2017-06-04 12:34
1. because it's hanging, so i can't get ExitCode
2. the output of adb.exe just like this
```
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>taskkill /f /im:adb.exe
成功: 已终止进程 "adb.exe"，其 PID 为 14048。

C:\WINDOWS\system32>adb connect 127.0.0.1:21503
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
unable to connect to 127.0.0.1:21503: cannot connect to 127.0.0.1:21503: 由于目标计算机积极拒绝，无法连接。 (10061)

C:\WINDOWS\system32>adb connect 127.0.0.1:21503
adb server version (31) doesn't match this client (39); killing...
* daemon started successfully *
connected to 127.0.0.1:21503

C:\WINDOWS\system32>
```

3. if i read standard error first not standard output, it hangs
4. i run you code, then get the whole correct output, but it still hangs, can't exit
```
* daemon not running. starting it now on port 5037 * 
* daemon started successfully * 
connected to 127.0.0.1:21503 
```

**Comment by madelson** [comment] 2017-06-04 12:42
@xjfnet for #1, can you not pull result.ExitCode before getting the output?

**Comment by xjfnet** [comment] 2017-06-04 12:56
i can't pull ExitCode, it hangs when read command.Result.ExitCode

but run adb.exe in command prompt, the errorlevel is 0
```
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>taskkill /f /im:adb.exe
成功: 已终止进程 "adb.exe"，其 PID 为 2964。

C:\WINDOWS\system32>adb connect 127.0.0.1:21503
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
connected to 127.0.0.1:21503

C:\WINDOWS\system32>echo %errorlevel%
0

C:\WINDOWS\system32>
```
to test this issue youself, you just need adb.exe version 1.0.31, "127.0.0.1:21503" can be anything
example: adb connect xxx
```

C:\WINDOWS\system32>taskkill /f /im:adb.exe
成功: 已终止进程 "adb.exe"，其 PID 为 2216。

C:\WINDOWS\system32>adb connect xxx
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
unable to connect to xxx:5555: cannot resolve host 'xxx' and port 5555: 不知道这样的主机。 (11001)

C:\WINDOWS\system32>
```

**Comment by madelson** [comment] 2017-06-04 13:55
@xjfnet very interesting. If I'm reading your responses correctly, `command.Result` returned when running #4 from my first set of questions (because the hang was on the StandardOutput line), but when you ran the revised code with `ExitCode` `command.Result` was not returning. Is that right?

Can you point me to where I can download the specific `adb.exe` version needed to repro this?

**Comment by xjfnet** [comment] 2017-06-04 14:24
i search "adb 1.0.31 zip" with bing, and get this https://hostr.co/bBxxj7gFfMlW
i run the code with this adb.exe, it can repro this issue
important: to repro this issue kill adb.exe first is necessary

**Comment by xjfnet** [comment] 2017-06-04 17:13
![default](https://cloud.githubusercontent.com/assets/4667005/26763775/fe8bb3a4-498b-11e7-8eb8-95f0bf2423ea.png)
line 16. WaitForExit() is done
line 17. hangs

**Comment by madelson** [comment] 2017-06-04 20:03
Hi @xjfnet I've dug into this a bit more and replicated your issue. I don't have a solution yet but I'm beginning to understand what it happening a bit more:

First, when adb.exe runs, it creates a background process which is also adb.exe if there isn't one already. That process keeps running even after adb.exe dies. That's why it seems like timeout isn't killing the process (it is).

Second, if you run adb.exe when the background process already exists, everything works nicely and you can get text from standard out. The process exists normally.

However, in the first case where the background process is created, something very strange happens. Basically, the main process will not exit and even when it does the standard output stream does not close. In all cases I've seen previously, the standard IO streams die immediately upon the process's exiting. 

This is ultimately what causes the hanging behavior. MedallionShell will not let Command.Result return until both the process has exited AND all bytes from the output streams have been buffered or consumed (generally a helpful feature). In this case since standard output never closes the IO is never seen as completing and the entire thing hangs. 

At this point, I don't feel like I can implement a fix until I understand what is going on under the hood a bit better. I've asked a question on StackOverflow (https://stackoverflow.com/questions/44358255/standardoutput-stream-staying-open-after-process-exits) that includes a self-contained reproduction of the strange behavior.

In the meantime, a workaround for your use-case might be to simply run adb.exe twice. The first time, use the `StartInfo` option to disable redirection for all streams. That run will make sure that the daemon is created. Then run it again normally.

**Comment by xjfnet** [comment] 2017-06-05 04:56
the codes below can run to the end withou hanging 
```cs
    class Program
    {
        static void Main()
        {
            Process.GetProcessesByName("adb").ToList().ForEach(x => x.Kill());

            var process = new Process();
            /* adb version 1.0.31 */
            process.StartInfo.FileName = @"D:\Program Files\Microvirt\MEmu\adb.exe";
            /* adb version 1.0.39 */
            process.StartInfo.FileName = @"D:\Android\android-sdk\platform-tools\adb.exe";
            process.StartInfo.Arguments = "connect 127.0.0.1:21503";
            process.StartInfo.UseShellExecute = false;
            process.StartInfo.CreateNoWindow = true;
            process.StartInfo.RedirectStandardInput = true;
            process.StartInfo.RedirectStandardOutput = true;
            process.StartInfo.RedirectStandardError = true;

            process.EnableRaisingEvents = true;

            process.Exited += (sender, args) =>
            {
                Console.WriteLine("process exited with code {0}", process.ExitCode);
            };

            process.Start();

            var output = new MemoryStream();
            var readOutputThread = new Thread(() =>
            {
                ReadStream(process.StandardOutput.BaseStream, output);
            })
            { IsBackground = true };
            readOutputThread.Start();

            var error = new MemoryStream();
            var readErrorThread = new Thread(() =>
            {
                ReadStream(process.StandardError.BaseStream, error);
            })
            { IsBackground = true };
            readErrorThread.Start();

            process.WaitForExit();


            output.Position = 0;
            error.Position = 0;
            var outputText = new StreamReader(output).ReadToEnd();
            var errorText = new StreamReader(error).ReadToEnd();

            Console.WriteLine(outputText);
            Console.WriteLine(errorText);

            Console.WriteLine(readOutputThread.ThreadState);
            Console.WriteLine(readErrorThread.ThreadState);
        }
        public static void ReadStream(Stream src, Stream dst)
        {
            var buffer = new byte[1024 * 4];
            while (true)
            {
                var task = src.ReadAsync(buffer, 0, buffer.Length);
                var count = task.Result;
                if (count == 0)
                {
                    Console.WriteLine("reach the end of the stream");
                    return;
                }
                if (task.Exception != null)
                {
                    Console.WriteLine(task.Exception.ToString());
                    return;
                }
                dst.Write(buffer, 0, count);
            }
        }

    }

```
the result of the program with adb version 1.0.31 is :
```
process exited with code 0
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
unable to connect to 127.0.0.1:21503:21503


Background, WaitSleepJoin
Background, WaitSleepJoin
```
and the result with adb version 1.0.39 is :
```
reach the end of the stream
reach the end of the stream
process exited with code 0
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
unable to connect to 127.0.0.1:21503: cannot connect to 127.0.0.1:21503: 由于目标计算机积极拒绝，无法连接。 (10061)


Stopped
Stopped
```

maybe there is some bug in the adb.exe version 1.0.31, the end of the stdout/sdterr can't be reached

**Comment by madelson** [comment] 2017-06-05 11:10
@xjfnet yes the older version of that process definitely behaves strangely. I'm very curious to know what exactly it is doing under the hood that causes this behavior.

**Comment by madelson** [comment] 2017-07-01 14:38
@xjfnet I looked into this a bit more. From what I can tell, there is really no for the .NET code to safely untangle itself from this particular process. Because the pipes opened from the process are synchronous, not asynchronous, cancellation doesn't work. I even tried manually closing the file handle: that doesn't even break the read. 

That means that even if we forced an exit via a layered-on cancellation mechanism, we'd have a memory leak due to the underlying task that never completes. This in turn means that this "solution" ends up being equivalent to you calling Command.Task.Wait(CancellationToken) in your code to avoid hanging (which would work today).

Since this is the only process where I've seen this; I'm going to close this and leave the code as-is for now. I will revisit if more instances of such processes are causing issues for people, of if we stumble upon a robust solution for this issue.

Thanks for your help in investigating. It's a very interesting problem.

**Closed as completed by madelson** 2017-07-01 14:38 UTC

**Comment by compucorss** [comment] 2017-12-19 03:29
I know this is closed, but I had a heck of a time this week fighting with  ReadToEnd() that hung for five or more minutes.  It turns out that my HttpRequest request needed a request.Proxy = null;  After that, it worked like a charm.  Hoping it helps someone.

**Comment by madelson** [comment] 2017-12-19 09:41
@compucorss I'm not sure I follow your scenario. Was the HttpRequest without the proxy setting happening in the external process? What was the connection to StandardOut? In general, ReadToEnd() cannot return until the external process either closes StandardOut or, more likely, exits. Therefore anything that would cause the external process to hang (e. g. an infinite loop, deadlock, etc) will cause ReadToEnd() to hang.

**Comment by compucorss** [comment] 2017-12-19 12:50
Sorry, I should've mentioned that it had nothing to do with the code above.  Was just commenting about a separate problem that I had.  Can't get to the machine now, but I was working on a local installment trying to call out to a GET API of a vendor.  I will post the code if you're interested later.  Thanks!
